config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :books, only: [:index, :show, :create] do
    resources :reviews, only: [:new, :create]
    # resources :user_books, only: [:create]
    resources :user_reactions, only: [:create]
  end

  resources :communities, only: [:index, :new, :create, :edit, :update, :show] do
    # resources :user_communities, only: [:create]
    resources :messages, only: [:create, :destroy]
  end

  resources :reviews, only: [:edit, :update, :destroy]
  resources :user_communities, only: [:index, :create, :destroy]
  resources :user_books, only: [:index, :destroy, :edit, :update]
  post "user_books/:id", to: "user_books#create", as: :add_book
  resources :user_reactions, only: [:index]


  get "discover", to: "books#discover", as: :discover
  get "recommendation", to: "books#recommendation", as: :recommendation
  get "my-profile", to: "pages#my_profile", as: :my_profile
  get "profile/:user_id", to: "pages#user_profile", as: :profile


  resources :surveys, only: [:create] do
    resources :answers, only: [:new, :create]
  end
end

app/models/user_community.rb
class UserCommunity < ApplicationRecord
  belongs_to :user
  belongs_to :community


  validates :user_id, :community_id, presence: true
end

app/controllers/user_communities_controller.rb
class UserCommunitiesController < ApplicationController
  before_action :set_user_community, only: [:destroy]

  def index
    @user_communities = current_user.communities
  end

  def create
    @community = Community.find(params[:id])
    @user_community = UserCommunity.new
    @user_community.user_id = current_user.id
    @user_community.community_id = @community.id

    if @user_community.save
      redirect_to user_communities_path, notice: "You've joined a book community"
    else
      redirect_to communities_path(@community), alert: 'Unable to join this community.'
    end
  end

  def destroy
    @user_community.destroy
    redirect_to user_communities_path, status: :see_other, notice: "You unfollowed a community"
  end

  private

  def set_user_community
    @user_community = UserCommunity.find(params[:id])
  end
end

app/views/user_communities/index.html.erb
<div class= "my-com-container">
  <div class="white-arrow">
    <%= link_to my_profile_path do %>
      <button class="return-arrow">
        <%= image_tag "back_arrow.png"%>
      </button>
    <% end  %>
  </div>

  <div class="bookshelf-title text-center my-5 pb-3">
    <h1 style="font-weight: 600; color: #B9D9EC; pb-3; font-size: 30px; ">My communities</h1>
    <div style="font-size: 20px;">
      <% if current_user.communities.empty? %>
        <p>You haven't joined any book community yet</p>
      <% else %>
        <p>You've joined <%= current_user.communities.count %> <%= current_user.communities.count > 1 ? "book communities" : "book community" %></p>
      <% end %>
    </div>
  </div>

   <br>

  <%= link_to communities_path do%>
    <%= image_tag "explore_icon.png"%><h2 class="explore-hover" style="text-center">Explore more communities!</h2>
  <% end %>

  <div class="custom-container" style="padding-bottom: 80px;">
    <% current_user.user_communities.each do |user_community| %>
    <%= link_to user_community_path(user_community),
                data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to unfollow this community?" },
                class: "unfollow-btn" do%>
        <%= image_tag "delete.png" %>
      <% end %>
      <%= link_to community_path(user_community.community), class: "com-thumbnail-link" do %>
        <div class="com-thumbnail">
          <div class="background-img" style="background-image: url('<%= user_community.community.image %>'); width: 348px; height: 167px; background-size: cover; background-position: center;">
            <h1 class="com-title"><%= user_community.community.name %></h1>
            <div class="followers">
              <%= image_tag "community-thumbnail.png" %> <p><%= user_community.community.users.count %> <%= user_community.community.users.count == 1 ? "follower" : "followers" %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>