config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :books, only: [:index, :show, :create] do
    resources :reviews, only: [:new, :create]
    # resources :user_books, only: [:create]
    resources :user_reactions, only: [:create]
  end

  resources :communities, only: [:index, :new, :create, :edit, :update, :show] do
    # resources :user_communities, only: [:create]
    resources :messages, only: [:create, :destroy]
  end

  resources :reviews, only: [:edit, :update, :destroy]
  resources :user_communities, only: [:index, :create, :destroy]
  resources :user_books, only: [:index, :destroy, :edit, :update]
  post "user_books/:id", to: "user_books#create", as: :add_book
  resources :user_reactions, only: [:index]


  get "discover", to: "books#discover", as: :discover
  get "recommendation", to: "books#recommendation", as: :recommendation
  get "my-profile", to: "pages#my_profile", as: :my_profile
  get "profile/:user_id", to: "pages#user_profile", as: :profile


  resources :surveys, only: [:create] do
    resources :answers, only: [:new, :create]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_homesearch.html.erb
<div class="search-container">
  <%= form_with url: books_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :search,
          params[:search],
          class: "form-control",
          placeholder: "Search for books..." %>
    <%# <%= submit_tag "Search", class: "btn" %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div data-controller="display-form">
  <div class="navbar">
    <ul id="main-links">
      <li>
        <%= link_to root_path, data: { action: "click->navbar#highlight" } do %>
          <div>
            <%= image_tag "Component 1.svg", alt: "Additional Icon", class: "d-none", data: { navbar_target: "menu_icon"} %>
          </div>
          <div>
            <%= image_tag "home-thin.svg", alt: "Home Icon", class: "icon" %>
          </div>
          <span>Home</span>
        <% end %>
      </li>

      <li>
        <%= link_to books_path, data: { action: "click->navbar#highlight" } do %>
          <div>
            <%= image_tag "Component 1.svg", alt: "Additional Icon", class: "d-none", data: { navbar_target: "menu_icon"} %>
          </div>
          <div>
            <%= image_tag "search-thin.svg", alt: "Search Icon", class: "icon" %>
          </div>
          <span>Search</span>
        <% end %>
      </li>

      <li>
        <%= link_to root_path, data: { action: "click->display_form#render" } do %>
          <div>
            <%= image_tag "Component 1.svg", alt: "Additional Icon", class: "d-none", data: { navbar_target: "menu_icon"} %>
          </div>
          <div>
            <%= image_tag "discover.svg", alt: "Discover Icon", class: "icon" %>
          </div>
          <span>Discover</span>
        <% end %>
      </li>

      <li>
        <%= link_to communities_path, data: { action: "click->navbar#highlight" } do %>
          <div>
            <%= image_tag "Component 1.svg", alt: "Additional Icon", class: "d-none", data: { navbar_target: "menu_icon"} %>
          </div>
          <div>
            <%= image_tag "community.svg", alt: "Community Icon", class: "icon" %>
          </div>
          <span>Community</span>
        <% end %>
      </li>

      <li>
        <%= link_to my_profile_path, data: { action: "click->navbar#highlight" } do %>
          <div>
            <%= image_tag "Component 1.svg", alt: "Additional Icon", class: "d-none", data: { navbar_target: "menu_icon"} %>
          </div>
          <div>
            <%= image_tag "profile.svg", alt: "Profile Icon", class: "icon" %>
          </div>
          <span>Profile</span>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_reviews.html.erb
<!-- Review Section -->
<!-- Add New Review Section -->
<div class="review-comment-container">
  <% if current_user %>
    <% if @book.reviews.any? { |review| review.user_id == current_user.id } %>
      <p> We've got your review! Thanks for sharing</p>
      <%# </div> %>
    <% else %>
      <%= simple_form_for [@book, @review] do |f| %>
        <%= f.input :comment, class: "reviewbox", label: "Comment", placeholder: "Leave a review ✍🏻" %>
        <%# <p class="rating-p-text">Rating</p> %>
        <%= f.select :rating, options_for_select([1, 2, 3, 4, 5], @review.rating), { prompt: "Rating 1-5 ⭐️" } ,class: "rating-dropdown" %>
        <%= f.submit "Submit Review", class: "add-submit-buttons" %>
      <% end %>
    <% end %>
  <% end %>

<!-- Show Existing Reviews Section -->
<div class="existing-container">
<ul>
  <% @reviews.each do |review| %>
    <li>
    <div class="all-user-container">
      <div id="review-<%= review.id %>">
        <div class="review-profile-info">
          <div class="review-user-image">
            <%= image_tag(review.user.photo, style: "width: 50px; height: 50px; border-radius: 50%; object-fit:cover;") %>
          </div>
          <strong class="review-current-user-name">
            <%= review.user.username if current_user.username == review.user.username %>
          </strong>
          <strong class="review-other-user-name">
            <%= link_to review.user.username, profile_path(user_id: review.user.id) if current_user.username != review.user.username %>
          </strong>
          <i class="review-timestamp">• Published on <%= review.created_at.strftime("%a %b %e at %l:%M %p") %></i>
        </div>

        <div class="review-content">
          <% review.rating.times do %>
            <i class="fa-solid fa-star"></i>
          <% end %>
          <% (5 - review.rating).times do %>
            <i class="fa-regular fa-star"></i>
          <% end %>
          <p><%= review.comment %></p>
        </div>

        <% if current_user && review.user_id == current_user.id %>
          <p>
            <%= link_to review_path(review), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "review-delete" do %>
              <i class="fa-solid fa-trash"></i> Delete review
            <% end %>
          </p>
        <% end %>
      </div>
      </div>
    </li>
  <% end %>
</ul>
</div>
</div>