config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :books, only: [:index, :show, :create] do
    resources :reviews, only: [:new, :create]
    # resources :user_books, only: [:create]
    resources :user_reactions, only: [:create]
  end

  resources :communities, only: [:index, :new, :create, :edit, :update, :show] do
    # resources :user_communities, only: [:create]
    resources :messages, only: [:create, :destroy]
  end

  resources :reviews, only: [:edit, :update, :destroy]
  resources :user_communities, only: [:index, :create, :destroy]
  resources :user_books, only: [:index, :destroy, :edit, :update]
  post "user_books/:id", to: "user_books#create", as: :add_book
  resources :user_reactions, only: [:index]


  get "discover", to: "books#discover", as: :discover
  get "recommendation", to: "books#recommendation", as: :recommendation
  get "my-profile", to: "pages#my_profile", as: :my_profile
  get "profile/:user_id", to: "pages#user_profile", as: :profile


  resources :surveys, only: [:create] do
    resources :answers, only: [:new, :create]
  end
end

app/views/pages/home.html.erb
<div class="custom-home-container">
  <div class="header-container">
    <div class="logo-container">
      <h2 class="logo">Storigo</h2>
    </div>

    <div class="login-home-container">
      <% if !current_user %>
        <%= link_to "Log in", new_user_registration_path, class: "login_button" %>
      <% else %>
        <div>
          <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: "delete" }, class: "logout_button" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="image-container">
    <%= image_tag "home.png", alt: "Front-Page-Image", class: "image-class" %>
  </div>

  <div class="h2-home">
    <h2>Find a story that matches your mood</h2>
  </div>

  <div data-controller="display-form">
    <div class="home-button-container">
      <div>
        <button class="discover_button" data-action="click->display-form#render">
          <div>
            <%= image_tag "material-symbols-rocket-outline.svg", alt: "Discover Icon", class: "discover-icon" %>
          </div>
          Discover
        </button>
      </div>
    </div>

    <div class="modal modal-1 hidden" data-display-form-target="modal">
      <div>
        <%= render "books/discover" %>
        <button data-action="click->display-form#close" class="close-button">
          <%= image_tag "close.svg", alt: "Close Icon", class: "close-icon" %>
        </button>

      </div>
    </div>
  </div>

  <div data-controller="trending">
    <div class="trending-container">
      <div class="trend-container-2">
        <h2 class="trend">Trending</h2>
        <div>
          <%= image_tag "fire-department-outline-rounded.svg", alt: "Fire Icon", class: "fire-icon" %>
        </div>
      </div>
    </div>

    <div class="caro-trending-container">
          <div id="booksCarousel" class="carousel slide" style="padding-bottom:20px;" data-bs-ride="carousel">

    <div class="carousel-inner" style="margin: auto;">
          <% @books.each_slice(3).with_index do |books_group, index| %>
            <div class="carousel-item <%= 'active' if index == 0 %>">
              <div class="d-flex justify-content-center">
                <% books_group.each do |book| %>
                  <div class="">
                    <%= link_to book_path(book) do %>
                      <div class="d-flex flex-column align-items-center justify-content-center book-card">
                        <%= image_tag(book.cover_image, alt: book.title, class: "my-bookshelf-book-trend m-3") %>
                        <h5 class="text-center my-books-title-trend"><%= book.title %></h5>
                        <p class="text-center trend-author">by <%= book.author.tr('[]', '').split(',').map(&:strip).join(', ') %></p>
                      </div>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#booksCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#booksCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
   <!-- div data-trending-target="book">
      <div class="img-fluid pb-4 book visible" style="margin-top: -70px;">
        <%= image_tag "michelle.png", alt: "Trending-Image", class: "image-trend" %>
      </div>

      <div class="book visible">
        <%= image_tag "rating.svg", alt: "Ratings", class: "rating-trend" %>
      </div>

      <div class="trend-title-container">
        <div class="trend-title">
          <h3>Becoming</h3>
        </div>
      </div>

      <div class="trend-author">
        <h4>by Michelle Obama</h4>
      </div>
    </div-->

  <!-- TEST -->
    <%# <div class="book hidden" data-trending-target="book">
      <div class="img-fluid pb-4" style="margin-top: -70px; box-shadow: 8px 6px 12px 0px rgba(185, 217, 236, 0.20);">
        <%= image_tag "harry_potter.jpg", alt: "Trending-Image", class: "image-trend" %>
      <%# </div>

      <div>
        <%= image_tag "rating.svg", alt: "Ratings", class: "rating-trend" %>
      <%# </div>

      <div class="trend-title-container">
        <div class="trend-title">
          <h3>Harry Potter and the Philosopher's Stone</h3>
        </div>
      </div>

      <div class="trend-author">
        <h4>by J.K. Rowling</h4>
      </div>
    </div>

    <button data-action="click->trending#move">click</button>
  </div> %>
  <!-- TEST -->

  <div class="my-home-container">
    <h1 class="community-h">
    <%= image_tag "community-vector.svg", alt: "Community Icon", class: "community-icon" %>
    Communities
      </h1>

<!-- Add Carousel Below Communities -->
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators-home">
    <% @communities.each_with_index do |_, index| %>
      <button type="button" id="toggles-home" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="<%= index %>" class="<%= 'active' if index.zero? %>" aria-current="<%= 'true' if index.zero? %>" aria-label="Slide <%= index + 1 %>"></button>
    <% end %>
  </div>
  <div class="carousel-inner-home">
    <% @communities.each_with_index do |community, index| %>
      <div class="carousel-item <%= 'active' if index.zero? %>">
        <%= link_to community_path(community) do %>
          <div class="com-thumbnail">
            <div class="background-img-carousel" style="background-image: url('<%= community.image %>'); width: 348px; height: 167px; background-size: cover; background-position: center;">
              <h1 class="com-title"><%= community.name %></h1>
              <div class="followers">
                <%= image_tag "community-thumbnail.png"%> <p><%= community.users.count %> <%= community.users.count == 1? "follower" : "followers" %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>





  </div>
</div>
</div>

app/views/pages/my_profile.html.erb
<div class="my-profile-container">
  <h1 class="profile-title">Profile</h1>

  <div class="img-user-container">
    <!-- Image Container -->
    <div class="image-placement">
      <%= image_tag(current_user.photo, class: "profile-img") if current_user.photo.present? %>
    </div>
    <!-- Username Container -->
    <div class="username-container ms-3">
      <p class="username-title"><%= current_user.username %></p>
      <p>Member since <%= current_user.created_at.strftime("%B %d, %Y") %></p>
    </div>
  </div>

<div class="link-container">
  <div class="profile-links">
    <p class="edit-profile-link">
      <%= image_tag "edit_profile.svg", alt: "Profile Icon", class: "profile-icon" %>
      <%= link_to "Edit Profile", edit_user_registration_path %>
    </p>


    <p class="edit-profile-link">
      <%= image_tag "bookshelf.svg", alt: "Bookshelf Icon", class: "bookshelf-icon" %>
      <%= link_to "My bookshelf", user_books_path %>
    </p>

    <p class="edit-profile-link">
      <%= image_tag "Community-white.svg", alt: "Cookshelf Icon White", class: "community-white-icon" %>
      <%= link_to "My communities", user_communities_path, class: "community-p" %>
    </p>

    <p class="edit-profile-link">
      <%= image_tag "recommendation.svg", alt: "Recommendation Icon", class: "recommendation-icon" %>
      <%= link_to "Recent recommendation", user_reactions_path, class: "community-p" %>

    </p>
<%#
  <p class="edit-profile-link">
  <%= image_tag "graph.svg", alt: "Graph Icon", class: "graph-icon" %>
  <%# Reading tracker
  </p> %>

  <%# <div class="community-center"> %>
  </div>

  </div>
</div>

app/views/pages/profile.html.erb
<h1><%= @user_profile.username %></h1>

app/views/pages/user_profile.html.erb
<div class="bookshelf" data-controller="modal">
  <div class="bookshelf-title text-center my-5 pb-3">
    <h1 class="pb-3">
      <%= image_tag(@user_profile.photo, class: "profile-img") if @user_profile.photo.present? %>
      <%= @user_profile.username %>'s bookshelf
    </h1>
    <% if @user_profile.books.count > 0 %>
      <p><%= @user_profile.books.count %> <%= @user_profile.books.count > 1 ? "books" : "book" %> are added to this bookshelf 🤓</p>
    <% else %>
      <p>No books have been added to this bookshelf yet.</p>
    <% end %>
  </div>

  <div class="row">
    <% @user_profile.user_books.each do |user_book| %>
      <div class="col-6 d-flex flex-column align-items-center bookshelf-bookcover mt-5">
        <p>
          <%= link_to book_path(user_book.book) do %>
            <%= image_tag(user_book.book.cover_image, alt: user_book.book.title, class: "my-bookshelf-book mb-3") %>
          <% end %>
        </p>
        <p>
          <h5 class="text-center my-books-title"><%= user_book.book.title %></h5>
        </p>
        <p class="text-center bookshelf-author">
          by <%= user_book.book.author.tr('[]', '').split(',').map(&:strip).join(', ') %>
        </p>

        <!-- Progress Bar -->
        <div class="progress-word">
          <% if user_book.status == "In progress" %>
            <p>Status: <%= user_book.status %></p>
            <div class="progress-container">
              <progress value="<%= user_book.pages_read %>" max="<%= user_book.book.number_of_pages %>"></progress>
              <p><%= user_book.pages_read %> / <%= user_book.book.number_of_pages %> pages read</p>
            </div>
          <% else %>
            <p>Status: Completed</p>
            <div class="progress-container">
              <progress value="<%= user_book.book.number_of_pages %>" max="<%= user_book.book.number_of_pages %>"></progress>
            </div>
            <p><%= user_book.book.number_of_pages %> / <%= user_book.book.number_of_pages %> pages</p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>