config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :books, only: [:index, :show, :create] do
    resources :reviews, only: [:new, :create]
    # resources :user_books, only: [:create]
    resources :user_reactions, only: [:create]
  end

  resources :communities, only: [:index, :new, :create, :edit, :update, :show] do
    # resources :user_communities, only: [:create]
    resources :messages, only: [:create, :destroy]
  end

  resources :reviews, only: [:edit, :update, :destroy]
  resources :user_communities, only: [:index, :create, :destroy]
  resources :user_books, only: [:index, :destroy, :edit, :update]
  post "user_books/:id", to: "user_books#create", as: :add_book
  resources :user_reactions, only: [:index]


  get "discover", to: "books#discover", as: :discover
  get "recommendation", to: "books#recommendation", as: :recommendation
  get "my-profile", to: "pages#my_profile", as: :my_profile
  get "profile/:user_id", to: "pages#user_profile", as: :profile


  resources :surveys, only: [:create] do
    resources :answers, only: [:new, :create]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :user_books, dependent: :destroy
  has_many :user_reactions
  has_many :users, through: :user_books
  validates :title, :description, :author, :category,
            :number_of_pages, :publish_date, :cover_image, :api_id, presence: true

  include PgSearch::Model
    pg_search_scope :search_by_title_and_author,
    against: [ :title, :author ],
    using: {
    tsearch: { prefix: true }
  }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_item, only: [:show]

  def index
    if params[:search].present?
      user_input = params[:search]
      fetch_and_save_books_from_api(user_input)
      @books_ai = Book.where("title ILIKE ?", "%#{user_input}%")
    else
      @books_ai = Book.all.sample(60)
    end
  end

def fetch_and_save_books_from_api(search_term)
  url = "https://api2.isbndb.com/books/#{search_term}?page=1&pageSize=20&column=title&language=en&shouldMatchAll=0"
  response = HTTP.headers("Content-Type": "application/json", "Authorization": ENV["ISBN_DB_API"]).get(url)
      if response.status.success?
        books = JSON.parse(response.body)["books"] || []
        books.each {|book_data| save_book_to_database(book_data)}
      end
end

  def save_book_to_database(book_data)
      return if Book.find_by(api_id: book_data["isbn13"].presence)
      Book.create(
      title: book_data["title"],
      author: book_data["authors"],
      description: book_data["synopsis"],
      category: book_data["subjects"],
      number_of_pages: book_data["pages"],
      publish_date: book_data["date_published"],
      cover_image: book_data["image"],
      api_id: book_data["isbn13"]
      )
  end

  def new
    @book = Book.new
  end

  def show
    @book_id = params[:book_id]
    @review = Review.new(book_id: @book_id)
    @reviews = Review.where(book_id: @book.id)
    @user_review = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def discover
    # render partial: "books/discover"
  end

  def recommendation
    @user_survey = current_user.surveys.last

    BookJob.perform_later(@user_survey, current_user)
  end

  private

  def set_item
    @book = Book.find(params[:id])
  end

  #RECOMMENDATION METHODS:

  def getRecommendations(mood)
  url = "https://api2.isbndb.com/books/#{mood}?page=1&pageSize=100&column=subject&language=en&shouldMatchAll=0"

  response = HTTP.headers("Content-Type": "application/json", "Authorization": ENV["ISBN_DB_API"]).get(url)
  book_data = JSON.parse(response.body)

  p book_data

  isbn13_numbers = book_data["books"].map { |item| item["isbn13"] }

  end

  def createBook(isbn13)

    url = "https://api2.isbndb.com/book/#{isbn13}"

    response = HTTP.headers("Content-Type": "application/json", "Authorization": ENV["ISBN_DB_API"]).get(url)
    book_data = JSON.parse(response.body)

    p book_data

    if book_data["errorMessage"] == "Not Found" || book_data["message"] == "Forbidden"
      puts "Unable to find book"
    elsif book_data["book"]["isbn13"].blank? && book_data["book"]["isbn"].blank?
      puts "Untrackable book... no ISBN"
    elsif Book.find_by(api_id: (book_data["book"]["isbn13"].presence || book_data["book"]["isbn"].presence).to_s)
      puts "Book already exists in the database"
    else
      title = book_data["book"]["title"] || book_data["book"]["title_long"]
      description = book_data["book"]["synopsis"] || "No description available"
      author =  if book_data["book"]["authors"] && !book_data["book"]["authors"].empty?
                    book_data["book"]["authors"].join(", ")
                else
                    book_data["book"]["authors"]
                end
      category =  if book_data["book"]["subjects"] && !book_data["book"]["subjects"].empty?
                      book_data["book"]["subjects"].join(", ")
                  else
                      "No categories available"
                  end
      number_of_pages = book_data["book"]["pages"].to_i || "No information available"
      publish_date = book_data["book"]["date_published"] || "No information available"
      cover_image = book_data["book"]["image"] || "No cover available"
      api_id = book_data["book"]["isbn13"].to_s || book_data["book"]["isbn"].to_s
      publisher = book_data["book"]["publisher"] || "No information available"

      new_book = Book.new(
        title: title,
        description: description,
        author: author,
        category: category,
        number_of_pages: number_of_pages,
        publish_date: publish_date,
        cover_image: cover_image,
        api_id: api_id,
        publisher: publisher
      )

      new_book.save!
      p "Book created!"
    end

  end

  def getISBNorder(isbn13_array, answer_category, answer_length, answer_style, answer_year)
    client = OpenAI::Client.new
    chatgpt_response = client.chat(parameters: {
      model: "gpt-4o-mini",
      messages: [{ role: "user", content: "
      Please give me 15 books which ISBN-13 number should be must from the #{isbn13_array} array and match the following:

      category: #{answer_category}
      around #{answer_length} pages
      style: #{answer_style}
      published #{if answer_year == "New releases"
                    "after 2020"
                  elsif answer_year == "Old but gold"
                    "before 2000"
                  else
                    "in any year"
                  end}

      Do not return anything else than the array. List from the most relevant to the least relevant. Also add a reason (from 200 to 400 characters) about why this suggestion was given.

      Return it in an array of ruby hashes (only with Keys ISBN and Reason)."
      }]
    })

    results = chatgpt_response["choices"][0]["message"]["content"][7..-4]
    converted_results = eval(results)

    converted_results.each do |result|
      isbn13_array.include?(result[:ISBN])
      createBook(result[:ISBN]) if isbn13_array.include?(result[:ISBN])
    end
  end
end

app/views/books/_book-details.html.erb
<h1><%= @book.title %></h1>
<p><%= @book.author %></p>
<p><%= @book.description %></p>
<p>Pages: <%= @book.number_of_pages %></p>
<p>Publication date: <%= @book.publish_date %></p>
<p>Publisher: <%= @book.publisher %></p>

app/views/books/_book_recommendations.html.erb
<% @book = books.first %>
<% @reason = books_with_reasons %>

<div data-controller="next-book" data-next-book-first-book-id-value="<%= @book.id %>">
  <div class="book-container modal-wrapper" data-controller="modal" data-next-book-target="book" data-recommendation-id="0">
    <p data-action="click->modal#details" class="see-details-toggle-recommend">
    <%= image_tag "Detail-2.svg", alt: "Detail Icon", class: "detail-icon" %>
    See details
  </p>
    <div class="book-cover">
      <%= image_tag(@book.cover_image, alt: @book.title) || "no cover available" %>
    </div>
    <div class="book-txt">
      <h2><%= @book.title %></h2>
      <p>by <%= @book.author %></p>
    </div>
    <div class="rec-btns">
      <div class="btn-wrapper">
        <button class="image-button" data-action="click->next-book#next" data-recommendation-id="0">
          <%= image_tag "reject.png", alt: "Click Me" %>
        </button>
        <%# <p>Not interested</p> %>
      </div>
      <div class="btn-wrapper">
        <%= link_to book_path(@book), class: "btn-link" do %>
          <button class="image-button" data-next-book-target="likeButton" data-action="click->next-book#likedFirst" data-recommendation-id="0">
            <%= image_tag "accept.png", alt: "Accept recommendation" %>
          </button>
        <% end %>
        <%# <p>Interested</p> %>
      </div>
    </div>

    <div data-controller="display-reason">
      <button data-action="click->display-reason#render" class="ai-prompt">
        <%= image_tag "question_mark.png", alt: "AI Prompt" %>
      </button>
      <div class="modal recommend-alt hidden" data-display-reason-target="modal">
        <div>
          <%= @reason.first[:reason] %>
          <button data-action="click->display-reason#close" class="close-button">
            <%= image_tag "close.svg", alt: "Close Icon", class: "close-2-icon" %>
          </button>
        </div>
      </div>
    </div>

      <div class="modal-2 hidden" data-modal-target="bookDetails">
      <div class = "modal-container">
        <h1><%= @book.title %></h1>
        <p><%= @book.author %></p>
        <p><%= @book.description %></p>
        <p>Pages: <%= @book.number_of_pages %></p>
        <p>Publication date: <%= @book.publish_date %></p>
        <p>Publisher: <%= @book.publisher %></p>
        <button data-action="click->modal#closeDetails" class="close-button">
        <%= image_tag "close.svg", alt: "Close Icon", class: "close-icon" %>
      </button>
      </div>
    </div>
  </div>

<% books[1..].each_with_index do |book, index| %>
  <div
    id="nex-book-<%= book.id %>"
    class="book-container modal-wrapper d-none"
    data-controller="modal"
    data-next-book-target="book"
    data-recommendation-id="<%= index + 1 %>"
    data-next-book-bookid-value="<%= book.id %>"
  >
    <p data-action="click->modal#details" class="see-details-toggle-recommend">
    <%= image_tag "Detail-2.svg", alt: "Detail Icon", class: "detail-icon" %>
    See details
  </p>
    <div class="book-cover">
      <%= image_tag(book.cover_image, alt: book.title) || "no cover available" %>
    </div>
    <div class="book-txt">
      <h2><%= book.title %></h2>
      <p>by <%= book.author %></p>
    </div>
    <div class="rec-btns">
      <div class="btn-wrapper">
        <button class="image-button" data-action="click->next-book#next" data-recommendation-id="<%= index + 1 %>">
          <%= image_tag "reject.png", alt: "Click Me" %>
        </button>
        <p>Not interested</p>
      </div>
      <div class="btn-wrapper">
        <%= link_to book_path(book), class: "btn-link" do %>
          <button class="image-button" data-next-book-target="likeButton" data-action="click->next-book#liked">
            <%= image_tag "accept.png", alt: "Accept recommendation" %>
          </button>
        <% end %>
        <p>Interested</p>
      </div>
    </div>

    <div data-controller="display-reason">
      <button data-action="click->display-reason#render" class="ai-prompt">
        <%= image_tag "question_mark.png", alt: "AI Prompt" %>
      </button>
      <div class="modal recommend-alt hidden" data-display-reason-target="modal">
        <div>
          <%= @reason[index + 1][:reason] %>
          <button data-action="click->display-reason#close" class="close-button">
            <%= image_tag "close.svg", alt: "Close Icon", class: "close-2-icon" %>
          </button>
        </div>
      </div>
    </div>

      <div class="modal-2 hidden" data-modal-target="bookDetails">
    <div class="modal-container">
      <h1><%=  book.title %></h1>
        <p><%= book.author %></p>
        <p><%= book.description %></p>
        <p>Pages: <%= book.number_of_pages %></p>
        <p>Publication date: <%= book.publish_date %></p>
        <p>Publisher: <%= book.publisher %></p>
      <button data-action="click->modal#closeDetails" class="close-button">
        <%= image_tag "close.svg", alt: "Close Icon", class: "close-icon" %>
      </button>
    </div>
  </div>
  </div>
<% end %>
</div>
</div>

app/views/books/_discover.html.erb
<div class="d-none" data-controller="survey" data-display-form-target="questionaire">
  <div data-display-form-target="question_1">
    <div data-survey-target="question_1">
      <%= simple_form_for [@survey, @answer], data: { survey_target: "survey"}, html: { class: "d-none" } do |f| %>
        <p><%= @questions.first.content %></p>
        <%= f.input :content, input_html: { data: { survey_target: "input"}} %>
        <%= f.input :question_id, input_html: { value: @questions.first.id }%>
      <% end %>
      <div class="mood-font">
        <p><%= @questions.first.content  %></p>
      </div>
  <div class="button-container">
        <button class="mood_button" data-survey-target="answer" data-answer="<%= @questions.first.answer_1 %>" data-action="click->survey#createAnswer"><%= @questions.first.answer_1 %></button>
        <button class="mood_button_2" data-survey-target="answer" data-answer="<%= @questions.first.answer_2 %>" data-action="click->survey#createAnswer"><%= @questions.first.answer_2 %></button>
        <button class="mood_button_3" data-survey-target="answer" data-answer="<%= @questions.first.answer_3 %>" data-action="click->survey#createAnswer"><%= @questions.first.answer_3 %></button>
        <button class="mood_button_4" data-survey-target="answer" data-answer="<%= @questions.first.answer_4 %>" data-action="click->survey#createAnswer"><%= @questions.first.answer_4 %></button>
        <button class="mood_button_5" data-survey-target="answer" data-answer="<%= @questions.first.answer_5 %>" data-action="click->survey#createAnswer"><%= @questions.first.answer_5 %></button>
      </div>
    </div>
  </div>

  <div class="d-none" data-survey-target="question_2">
    <%= simple_form_for [@survey, @answer], data: { survey_target: "survey"}, html: { class: "d-none" } do |f| %>
      <%= f.input :content, input_html: { data: { survey_target: "input"}} %>
      <%= f.input :question_id, input_html: { value: @questions.second.id }%>
    <% end %>
    <div class="mood-font">
      <p><%= @questions.second.content  %></p>
    </div>
    <div class="button-container">
      <button class="mood_button" data-survey-target="answer" data-answer="<%= @questions.second.answer_1 %>" data-action="click->survey#createAnswer"><%= @questions.second.answer_1 %></button>
      <button class="mood_button_2" data-survey-target="answer" data-answer="<%= @questions.second.answer_2 %>" data-action="click->survey#createAnswer"><%= @questions.second.answer_2 %></button>
      <button class="mood_button_3" data-survey-target="answer" data-answer="<%= @questions.second.answer_3 %>" data-action="click->survey#createAnswer"><%= @questions.second.answer_3 %></button>
      <button class="mood_button_4" data-survey-target="answer" data-answer="<%= @questions.second.answer_4 %>" data-action="click->survey#createAnswer"><%= @questions.second.answer_4 %></button>
      <button class="mood_button_5" data-survey-target="answer" data-answer="<%= @questions.second.answer_5 %>" data-action="click->survey#createAnswer"><%= @questions.second.answer_5 %></button>
    </div>
  </div>

  <div class="d-none" data-survey-target="question_3">
    <%= simple_form_for [@survey, @answer], data: { survey_target: "survey"}, html: { class: "d-none" } do |f| %>
      <%= f.input :content, input_html: { data: { survey_target: "input"}} %>
      <%= f.input :question_id, input_html: { value: @questions.third.id }%>
    <% end %>
    <div class="mood-font">
      <p><%= @questions.third.content  %></p>
    </div>
    <div class="button-container">
      <button class="mood_button" data-survey-target="answer" data-answer="<%= @questions.third.answer_1 %>" data-action="click->survey#createAnswer"><%= @questions.third.answer_1 %></button>
      <button class="mood_button_2" data-survey-target="answer" data-answer="<%= @questions.third.answer_2 %>" data-action="click->survey#createAnswer"><%= @questions.third.answer_2 %></button>
      <button class="mood_button_3" data-survey-target="answer" data-answer="<%= @questions.third.answer_3 %>" data-action="click->survey#createAnswer"><%= @questions.third.answer_3 %></button>
    </div>
  </div>

  <div class="d-none" data-survey-target="question_4">
    <%= simple_form_for [@survey, @answer], data: { survey_target: "survey"}, html: { class: "d-none" } do |f| %>
      <%= f.input :content, input_html: { data: { survey_target: "input"}} %>
      <%= f.input :question_id, input_html: { value: @questions.fourth.id }%>
    <% end %>
    <div class="mood-font">
      <p><%= @questions.fourth.content  %></p>
    </div>
    <div class="button-container">
      <button class="mood_button" data-survey-target="answer" data-answer="<%= @questions.fourth.answer_1 %>" data-action="click->survey#createAnswer"><%= @questions.fourth.answer_1 %></button>
      <button class="mood_button_2" data-survey-target="answer" data-answer="<%= @questions.fourth.answer_2 %>" data-action="click->survey#createAnswer"><%= @questions.fourth.answer_2 %></button>
      <%# <button data-survey-target="answer" data-answer="<%= @questions.fourth.answer_3 %>
      <%# " data-action="click->survey#createAnswer"><%= @questions.fourth.answer_3 %>
      <%# </button> %>
    </div>
  </div>

  <div class="d-none" data-survey-target="question_5">
    <%= simple_form_for [@survey, @answer], data: { survey_target: "survey"}, html: { class: "d-none" } do |f| %>
      <%= f.input :content, input_html: { data: { survey_target: "input"}} %>
      <%= f.input :question_id, input_html: { value: @questions.fifth.id }%>
    <% end %>
    <div class="mood-font">
      <p><%= @questions.fifth.content  %></p>
    </div>
    <div class="button-container">
      <button class="mood_button" data-survey-target="answer" data-answer="<%= @questions.fifth.answer_1 %>" data-action="click->survey#createAnswer"><%= @questions.fifth.answer_1 %></button>
      <button class="mood_button_2" data-survey-target="answer" data-answer="<%= @questions.fifth.answer_2 %>" data-action="click->survey#createAnswer"><%= @questions.fifth.answer_2 %></button>
      <button class="mood_button_3" data-survey-target="answer" data-answer="<%= @questions.fifth.answer_3 %>" data-action="click->survey#createAnswer"><%= @questions.fifth.answer_3 %></button>
    </div>
  </div>

  <div class="d-none" data-survey-target="final">
    <%= link_to "Get recommendation",  recommendation_path, class: "mood_button recommendation_button" %>
  </div>
</div>

app/views/books/_explore.html.erb
<div class="added-container">
<h1>A new chapter awaits!</h1>
<p>You successfully added a book to your bookshelf! Be sure to join the conversation and share your thoughts with others in the book communities.</p>

<div class="explore-link-container">
  <div class="explore-link">
    <%= link_to "Explore", communities_path %>
  </div>
</div>

<div class="bookshelf-link-container">
<div class="bookshelf-link">
    <%= link_to "Go to your bookshelf", user_books_path %>
</div>
</div>

</div>

app/views/books/_reason.html.erb
<%# <%= @books_with_reasons.first[:reason] %>

app/views/books/_recommendation-details.html.erb
<h1><%= @book.title %></h1>
<p><%= @book.author %></p>
<p><%= @book.description %></p>
<p>Pages: <%= @book.number_of_pages %></p>
<p>Publication date: <%= @book.publish_date %></p>
<p>Publisher: <%= @book.publisher %></p>

app/views/books/index.html.erb
<%= render "shared/homesearch" %>

<div class="container mt-4" style="
    padding-bottom: 80px">
  <div class="row">
    <% if @books_ai.present? %>
    <% @books_ai.each_with_index do |book, index| %>
      <% if index % 3 == 0 && index != 0 %>
        </div><div class="row">
      <% end %>

      <% if book.is_a?(Book) %>
        <%= link_to book_path(book) do %>

          <div class="results">
            <div class="search-card">
                <%= image_tag book.cover_image, class: "search-img"%>
              <div class="search-txt">

                  <h5 class="card-title" style="color: #B9D9EC"><%= book.title %></h5>
                  <% authors_array = book.author.is_a?(String) && book.author.start_with?("[") ? JSON.parse(book.author) : Array(book.author) %>
                  <br>

                  <p class="card-text-author" style="size:14px">by <%= authors_array.join(",") %></p>
                  <% if book.number_of_pages.present? %>
                    <span class="card-text"> <%= book.number_of_pages %> pages | </span>
                  <% end %>
                  <% if book.publish_date.present? %>
                    <span class="card-text"> <%= book.publish_date %></span>
                  <% end %>
              </div>

                <div class="to-bookshelf" data-controller="bookstatus">
                  <% if current_user.books.include?(book) %>
                   <div class="" data-bookstatus-target="checkmark">
                   <%= image_tag "checkmark.svg", alt: "checked icon" %>
                  </div>
                  <% else %>
                  <%= link_to add_book_path(id: book.id), data: {turbo_method: :post, bookstatus_target:"link", action: "bookstatus#removelink" } do %><%= image_tag "bookshelf_icon.png", alt:"Bookshelf icon"%>

                  <% end %>
                   <div class="d-none" data-bookstatus-target="checkmark">
                   <%= image_tag "checkmark.svg", alt: "checked icon" %>
                  </div>
                  <% end %>
                </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
    <%else%>
    <p>"Sorry, no book available."</p>
    <% end %>
  </div>
</div>

app/views/books/recommendation.html.erb
<%= turbo_stream_from "recommendations_#{current_user.id}" %>

<div class="loading-container" id="recommendations" data-controller="quote-rotator">
  <p><h1>Almost ready! Your next read is coming soon.</h1></p>
  <div class="loader"></div> <!-- Replace spinner with custom loader -->
  <br>
  <p id="quotes" data-quote-rotator-target="quote"><i>Loading...</i></p>
</div>


<%# <%= turbo_stream_from "recommendations" %> 

<%# <div class="loading-container" id="recommendations" data-controller="quote-rotator">
<p><h1>Almost ready! Your next read is coming soon.</h1></p> <div class="spinner-border" role="status">
<span class="sr-only">Loading...</span>
</div> <br> <p id="quotes" data-quote-rotator-target="quote"><i>Loading...</i></p> </div> %>

app/views/books/show.html.erb
<div class="book-container modal-wrapper" data-controller="modal">
  <p data-action="click->modal#details" class="see-details-toggle">
    <%= image_tag "Detail-2.svg", alt: "Detail Icon", class: "detail-icon" %>
    See details
  </p>

  <div class="book-cover">
    <%= image_tag(@book.cover_image, alt: @book.title) %>
  </div>

  <div class="book-txt">
    <h2><%= @book.title %></h2>
    <p>by <%= @book.author.tr('[]', '').split(',').map(&:strip).join(', ') %></p>
  </div>

  <% if current_user.books.include?(@book) %>
    <p class="already-added">This book has already been added to your bookshelf</p>
  <% else %>
    <%= button_to add_book_path(id: @book.id), id: "a-t-b-move",class: "add_to_bookshelf_button", data: { modal_target: "button", action: "modal#show", turbo_method: :post  } do %>
    <%= image_tag "add-to-bookshelf.svg", alt: "Add To Bookshelf Icon", class: "add-to-bookshelf-icon" %>
    Add to bookshelf
    <% end %>
  <% end %>

  <p class="buy-from">Buy from:</p>

  <div class="buy-link-container">
    <ul>
    <li class="amazon-item">
      <%= link_to "https://www.amazon.com/s?k=#{@book.title}", target: "_blank", class: "amazon-link" do %>
        <%= image_tag "amazon.svg", alt: "Amazon Icon", class: "amazon-icon" %>
      <% end %>
    </li>

    <li class="line-item">
      <%= image_tag "line.svg", alt: "Line Icon", class: "line-icon" %>
    </li>

      <li class="abc-item">
        <%= link_to "https://abc.nl/search#/query/title/#{@book.title}", target: "_blank", class: "abc-link" do %>
          <%= image_tag "abc-text-low.svg", alt: "ABC Icon", class: "abc-icon" %>
          <% end %>
        </li>
    </ul>
  </div>


  <h1 class="reviews-title">Reviews (<%= @book.reviews.count %>)</h1>
  <%= render "shared/reviews" %>


  <div class="modal yellow hidden" data-modal-target="modal">
    <div>
      <%= render "books/explore" %>
      <button data-action="click->modal#close" class="close-2-button">
        <%= image_tag "close.svg", alt: "Close Icon", class: "close-2-icon" %>
      </button>
    </div>
  </div>

  <div class="modal-2 hidden" data-modal-target="bookDetails">
    <div class="modal-container">
      <%= render "books/book-details" %>
      <button data-action="click->modal#closeDetails" class="close-button">
        <%= image_tag "close.svg", alt: "Close Icon", class: "close-icon" %>
      </button>
    </div>
  </div>
</div>